builder: swiitch from sq to gnupg
sq caused this error:
[1/2] STEP 11/14: RUN sq verify --signer-file release-key.pgp --detached archlinux-bootstrap-x86_64.tar.zst.sig archlinux-bootstrap-x86_64.tar.zst
No key to check checksum from 3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C
1 unknown checksum.
Error: Verification failed: could not fully authenticate any signatures
Error: building at STEP "RUN sq verify --signer-file release-key.pgp --detached archlinux-bootstrap-x86_64.tar.zst.sig archlinux-bootstrap-x86_64.tar.zst": while running runtime: exit status 1

I don't understand the reason for that. Also, the latest sq commands
from the arch wiki are different, but don't even work on alpine, because
the command `sq network wkd fetch` does not exist. So instead, I simply
switched to the alternative method on the arch wiki.